classes:
  0: unlabeled
  1: Non-Bone Active Tumor
  2: Bone Active Tumor
  3: Non-Bone Necrosis
  4: Bone Necrosis
  5: Normal Tissue
  6: Background
  7: Sparse Cellular Area
data:
  class_weights:
  - 0.0
  - 0.7967361008442999
  - 0.9621065027409531
  - 0.8139716422884785
  - 0.9604389227617818
  - 0.5096990504249257
  - 0.9724016033117096
  - 0.9846461776278514
  dataset: custom
  img_cols: same
  img_rows: same
  n_classes: 8
  path: ''
  train_file: /jhcnas5/chenzhixuan/data/OstPathData/DMMN/processed_data/train_tiles.txt
  train_split: train_aug
  val_file: /jhcnas5/chenzhixuan/data/OstPathData/DMMN/processed_data/val_tiles.txt
  val_split: val
loss:
  name: cross_entropy
model:
  arch: DMMN
  save_dir: /jhcnas5/chenzhixuan/checkpoints/DMMN-OST
  save_name: DMMN_ost_seg
training:
  batch_size: 48
  epochs: 50
  loss:
    name: cross_entropy
    size_average: true
  lr_schedule:
    name: poly
    power: 0.9
  optimizer:
    lr: 0.01
    momentum: 0.9
    name: SGD
    weight_decay: 0.0005
  print_interval: 10
  resume: null
  val_interval: 10000
  wandb:
    enabled: true
    entity: zchenhi
    name: DMMN-OST-Experiment
    notes: Osteosarcoma tissue segmentation using DMMN
    project: OST-DMMN
    tags:
    - OST
    - DMMN
    - segmentation
